FROM alpine

# CMD is so that docker run will execute whatever comes after CMD
CMD ["echo", "Hello!"]

# docker build -t hello .
# ~/dev/my_python_repo/docker/debian_pkg_install $ docker run --rm hello
# Hello!
# image size: 5.586 MB