FROM debian
ENV name Darwin
#ENTRYPOINT /bin/echo "Hello, $name!" # shell form
#ENTRYPOINT ["/bin/bash", "-c", "echo Hi, $name"]
#CMD ["echo", "Hello, Darwin!"]           drm d hostname outputs 770a13a6af73
#ENTRYPOINT ["echo", "Hello, Darwin!"]   # drm d hostname outputs Hello, Darwin! hostname
ENTRYPOINT ["echo", "Hello, "]CMD ["Darwin"]